#!/bin/bash
#
# This script is used to add the issue key to the commit message
# When used with the --message or --file option, it appends the issue key to the end of the commit message
# Otherwise, it prepends the issue key to the commit message in a way which makes it
# convenient to use with an editor

# Array of supported issue key prefixes
ISSUE_PREFIXES=("ENG" "CLO" "INF" "PLT" "UI")

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [ -n "$COMMIT_SOURCE" ]; then
    # Do not change amended commits
    if [ "$COMMIT_SOURCE" == "commit" ]; then
        exit 0
    fi
fi

# Get the current branch name
branch_name="$(git rev-parse --abbrev-ref HEAD)"

# Extract the issue key from the branch name using any of the supported prefixes
issue_key=""
for prefix in "${ISSUE_PREFIXES[@]}"; do
  found_key="$(echo "$branch_name" | grep -ioE "$prefix-[0-9]+" | tr '[:lower:]' '[:upper:]')"
  if [[ -n "$found_key" ]]; then
    issue_key="$found_key"
    break
  fi
done

if [[ -n "$issue_key" ]]; then
  # Check if issue key already exists in the commit message
  if ! grep -q "$issue_key" "$COMMIT_MSG_FILE"; then
    if [ "$COMMIT_SOURCE" == "message" ]; then
      # Append the issue key to the end of the commit message for message source
      echo -e "\n$issue_key" >> "$COMMIT_MSG_FILE"
    else
      # Prepend the issue key to the commit message for other sources
      sed -i.bak -e "1s/^/\n\n$issue_key /" "$COMMIT_MSG_FILE"
    fi
  fi
fi
